@startuml "Invoice Create Activity"
skinparam defaultFontSize 18
skinparam defaultFontName "Times New Roman"
|Ban quản lý|
start
:Chọn tạo hóa đơn theo phòng;
:Nhập tháng + chỉ số điện nước;
|Hệ thống|
:Kiểm tra dữ liệu;
:Tính tiền điện/nước/phí;
:Tạo hóa đơn;
|Ban quản lý|
:Nhận kết quả;
stop
@enduml
