@startuml "Disciplinary View Activity"
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
|Sinh viên|
start
:Đăng nhập;
:Vào mục Kỷ luật;
|Hệ thống|
:Lấy danh sách phiếu kỷ luật;
|Sinh viên|
:Xem chi tiết;
stop
@enduml
