@startuml
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam ArrowColor Black
skinparam ArrowThickness 1
skinparam shadowing false

actor "<b>Kế toán</b>" as Admin

together {
  usecase "<b>Xem danh sách hóa đơn</b>" as UC1
  usecase "<b>Xem chi tiết hóa đơn</b>" as UC2
  usecase "<b>Tạo hóa đơn thủ công</b>" as UC3
  usecase "<b>Tự động tạo hóa đơn theo phòng</b>" as UC4
  usecase "<b>Điều chỉnh bảng giá dịch vụ</b>" as UC9
}

together {
  usecase "<b>Cập nhật hóa đơn</b>" as UC5
  usecase "<b>Xóa hóa đơn</b>" as UC6
  usecase "<b>Phát hiện bất thường điện/nước</b>" as UC7
  usecase "<b>Tự động cập nhật hóa đơn quá hạn</b>" as UC8
  usecase "<b>Xem thống kê doanh thu</b>" as UC10
}

UC1 -[hidden]-> UC2
UC2 -[hidden]-> UC3
UC3 -[hidden]-> UC4
UC4 -[hidden]-> UC9

UC5 -[hidden]-> UC6
UC6 -[hidden]-> UC7
UC7 -[hidden]-> UC8
UC8 -[hidden]-> UC10

UC1 -[hidden]right-> UC5
UC2 -[hidden]right-> UC6
UC3 -[hidden]right-> Admin
Admin -[hidden]right-> UC7
UC4 -[hidden]right-> UC8
UC9 -[hidden]right-> UC10

UC1 <-- Admin
UC2 <-- Admin
UC3 <-- Admin
Admin --> UC4
Admin --> UC9

UC5 <-- Admin
UC6 <-- Admin
Admin --> UC7
Admin --> UC8
Admin --> UC10
@enduml
