@startuml "UC Phân rã - Phản ánh (Ban quản lý)"
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
left to right direction
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam ArrowColor Black
skinparam ArrowThickness 1
skinparam shadowing false

actor "<b>Ban quản lý</b>" as Admin

usecase "<b>Xem danh sách phản ánh</b>" as UC1
usecase "<b>Xem chi tiết phản ánh</b>" as UC2
usecase "<b>Cập nhật trạng thái xử lý</b>" as UC3
usecase "<b>Phản hồi cho sinh viên</b>" as UC4
usecase "<b>Xóa phản ánh</b>" as UC5
usecase "<b>Phân tích lại cảm xúc</b>" as UC6
usecase "<b>Xem thống kê phản ánh</b>" as UC7

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5
Admin --> UC6
Admin --> UC7
@enduml
