@startuml
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam ArrowColor Black
skinparam ArrowThickness 1
skinparam shadowing false

actor "<b>Ban quản lý</b>" as Admin

together {
  usecase "<b>Xem danh sách tài sản</b>" as UC1
  usecase "<b>Xem chi tiết tài sản</b>" as UC2
  usecase "<b>Thêm tài sản mới</b>" as UC3
  usecase "<b>Cập nhật thông tin tài sản</b>" as UC4
  usecase "<b>Xóa tài sản</b>" as UC5
  usecase "<b>Nhập tài sản vào kho</b>" as UC6
}

together {
  usecase "<b>Xuất tài sản đến phòng</b>" as UC7
  usecase "<b>Xem lịch sử nhập/xuất</b>" as UC8
  usecase "<b>Xem tài sản theo phòng/tòa</b>" as UC9
  usecase "<b>Điều chỉnh giới hạn tài sản/phòng</b>" as UC10
  usecase "<b>Xem thống kê tài sản</b>" as UC11
}

UC1 -[hidden]-> UC2
UC2 -[hidden]-> UC3
UC3 -[hidden]-> UC4
UC4 -[hidden]-> UC5
UC5 -[hidden]-> UC6

UC7 -[hidden]-> UC8
UC8 -[hidden]-> UC9
UC9 -[hidden]-> UC10
UC10 -[hidden]-> UC11

UC1 -[hidden]right-> UC7
UC2 -[hidden]right-> UC8
UC3 -[hidden]right-> Admin
Admin -[hidden]right-> UC9
UC4 -[hidden]right-> UC10
UC5 -[hidden]right-> UC11

UC1 <-- Admin
UC2 <-- Admin
UC3 <-- Admin
Admin --> UC4
Admin --> UC5
Admin --> UC6

UC7 <-- Admin
UC8 <-- Admin
Admin --> UC9
Admin --> UC10
Admin --> UC11
@enduml
