@startuml "UC Phân rã - Xác thực & Tài khoản"
left to right direction
skinparam usecase {
  BackgroundColor White
  BorderColor Black
}
skinparam actor {
  BackgroundColor White
  BorderColor Black
}
skinparam ArrowColor Black
skinparam ArrowThickness 1
skinparam shadowing false

actor "<b>Ban quản lý</b>" as Admin
actor "<b>Sinh viên</b>" as SV

usecase "<b>Đăng nhập</b>" as UC1
usecase "<b>Đăng xuất</b>" as UC2
usecase "<b>Quên mật khẩu</b>" as UC3
usecase "<b>Gửi OTP qua email</b>" as UC4
usecase "<b>Xác thực mã OTP</b>" as UC5
usecase "<b>Đặt lại mật khẩu mới</b>" as UC6
usecase "<b>Đổi mật khẩu</b>" as UC7

UC3 ..> UC4 : <<include>>
UC3 ..> UC5 : <<include>>
UC3 ..> UC6 : <<include>>

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC7
SV --> UC1
SV --> UC2
SV --> UC3
SV --> UC7
@enduml
