@startuml "Notification Send Activity"
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
|Ban quản lý|
start
:Nhập tiêu đề + nội dung;
:Chọn đối tượng (ALL/STUDENTS/SPECIFIC);
|Hệ thống|
:Kiểm tra dữ liệu;
:Tạo thông báo;
:Emit realtime qua socket.io;
:Gửi tới người nhận (qua socket);
|Client (Sinh viên)|
 :Nhận event "notification";
 :Hiển thị thông báo mới;
|Ban quản lý|
:Hoàn tất;
stop
@enduml
