@startuml
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
skinparam sequenceMessageSize 22
actor "Ban quản lý" as Admin
participant "Giao diện" as FE
participant "NotificationController" as NC
participant "NotificationService" as NS
participant "Socket.io" as WS
participant "Giao diện Sinh viên" as Student
database "CSDL" as DB


alt Gửi ALL
  Admin -> FE: Nhập nội dung
  FE -> NC: POST /api/notifications/send-all
  NC -> NS: sendToAllStudents(args)
  NS -> DB: INSERT notifications
  DB --> NS: OK
  NS -> WS: emitNotification(notification)
  WS -> Student: "notification" event
  NC --> FE: 201 Created
else Gửi SPECIFIC
  Admin -> FE: Chọn danh sách userIds
  FE -> NC: POST /api/notifications/send-specific
  NC -> NS: sendToSpecificUsers(args)
  NS -> DB: INSERT notifications
  DB --> NS: OK
  NS -> WS: emitNotification(notification)
  WS -> Student: "notification" event
  NC --> FE: 201 Created
end
@enduml
