@startuml "Registration Import Activity"
skinparam defaultFontSize 22
skinparam defaultFontName "Times New Roman"
|Ban quản lý|
start
:Chọn Import hồ sơ;
:Chọn Excel hoặc\nGoogle Sheets;
|Hệ thống|
:Nhận file hoặc URL;
if (Nguồn hợp lệ?) then (Có)
  :Đọc dữ liệu và\nvalidate thông tin;
  :Lưu hồ sơ tạm vào CSDL;
  :Tính toán điểm xét tuyển,\nđiểm ưu tiên ;
  fork
    :Xác thực ảnh minh chứng\n(Vision API);
  fork again
    :Phân loại vào các\nnhóm chỉ tiêu (Nhóm 1, 2, 3);
  end fork
  :Lưu điểm xét duyệt\n& đề xuất vào CSDL;
  |Ban quản lý|
  :Thông báo nhập hồ sơ\nvà xử lý điểm thành công;
  stop
else (Không)
  :Thông báo lỗi\nđịnh dạng/URL;
  |Ban quản lý|
  :Sửa nguồn và thử lại;
  stop
endif
@enduml
